name: Continuous Integration

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install and test
        run: |
          npm install
          npm test
        env:
          DBHOST: ${{ secrets.DBHOST }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}